<a href="https://colab.research.google.com/github/digitaldevansh2003/IDAV-/blob/main/Welcome_to_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import files
uploaded = files.upload()

Saving iris.csv to iris.csv


In [7]:
from copy import deepcopy
import numpy as np
import pandas as pd
import random

data = pd.read_csv('iris.csv') #reading from file
c1 = data['slength'].values
c2 = data['swidth'].values
c3 = data['plength'].values
c4 = data['pwidth'].values
X = np.array(list(zip(c1,c2,c3,c4)))

k=3
#no. of clusters (3 in the sample data)
k-means=KMeans(n_clusters=3,init='k-means++');

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[[6.853846  3.0769231 5.7153845 2.0538461]
 [5.8836064 2.7409837 4.3885245 1.4344262]
 [5.006     3.418     1.464     0.244    ]]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1.
 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 1.]
0.0
